In [1]:
import pandas as pd

In [4]:
pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,35],
              'col3': "sudhanshu kumar krish ineuron one"
    
    
})

col1  col2                               col3
0     1    45  sudhanshu kumar krish ineuron one
1     2    56  sudhanshu kumar krish ineuron one
2     3    67  sudhanshu kumar krish ineuron one
3     4    34  sudhanshu kumar krish ineuron one
4     5    35  sudhanshu kumar krish ineuron one

In [5]:
"sudhanshu kumar krish ineuron one".split()

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [8]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,35],
              'col3': "sudhanshu kumar krish ineuron one".split()
    
    
})

In [9]:
df

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    35        one

In [12]:
 # create col4 and perform square of all values of col1

df['col4'] = df['col1']**2

In [13]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    35        one    25

In [14]:
#create col5 where it is suppopse to hold first ch of each and every string of col3

df['col5'] = df['col3'].str[0]

In [15]:
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    35        one    25    o

In [ ]:
 # create col4 and perform square of all values of col1

In [17]:
def test(a):
    return a**2


In [19]:
df['col4'] = df['col1'].apply(test)

In [20]:
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    35        one    25    o

In [23]:
def test1(a):
    if a == 's':
        return 's'
    else:
        return 'z'

In [24]:
df['col6'] = df['col5'].apply(test1)

In [25]:
df

col1  col2       col3  col4 col5 col6
0     1    45  sudhanshu     1    s    s
1     2    56      kumar     4    k    z
2     3    67      krish     9    k    z
3     4    34    ineuron    16    i    z
4     5    35        one    25    o    z

In [ ]:
#create col7 where you should hold data which should be  be a length of each of every string available in col3

In [26]:
df['col7'] = df['col3'].apply(len)

In [27]:
df

col1  col2       col3  col4 col5 col6  col7
0     1    45  sudhanshu     1    s    s     9
1     2    56      kumar     4    k    z     5
2     3    67      krish     9    k    z     5
3     4    34    ineuron    16    i    z     7
4     5    35        one    25    o    z     3

In [ ]:
#create col8 which will hold log value  of col2

In [29]:
import math

In [30]:
df['col8'] = df['col2'].apply(math.log)

In [31]:
df

col1  col2       col3  col4 col5 col6  col7      col8
0     1    45  sudhanshu     1    s    s     9  3.806662
1     2    56      kumar     4    k    z     5  4.025352
2     3    67      krish     9    k    z     5  4.204693
3     4    34    ineuron    16    i    z     7  3.526361
4     5    35        one    25    o    z     3  3.555348

In [ ]:
# Numpy 

In [3]:
import numpy as np

In [4]:
l = ["sudh" , 1,2,3,4]

In [5]:
type(l)

list

In [6]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [7]:
type(np.array(l))

numpy.ndarray

In [16]:
a1 =  np.array([3,4,5,6,3.0])

In [11]:
a =np.array([[1,2] ,[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [14]:
a[1][1] #extract 4 from above array

4

In [17]:
a1

array([3., 4., 5., 6., 3.])

In [21]:
a1[1]

4.0

In [22]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [34]:
 a2 = np.array([1,2,3,4] ,ndmin =  4)

In [39]:
a2[0][0][0][0]  # extract 1 from avove array

1

In [40]:
a

array([[1, 2],
       [3, 4]])

In [41]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [42]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [43]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [44]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [45]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [46]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [47]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [48]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [ ]:
# martix is a child class of an array

In [49]:
np.fromfunction(lambda i ,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [52]:
np.fromfunction(lambda i ,j: i*j , (4,4) ,dtype =int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [53]:
np.mat(np.fromfunction(lambda i ,j: i*j , (4,4) ,dtype =int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [54]:
np.fromfunction(lambda i ,j,k: i*j*k , (3,3,2) ,dtype =int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [55]:
np.fromfunction(lambda i ,j,k: i*j*k , (4,3,2) ,dtype =int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [56]:
np.fromfunction(lambda i ,j,k,p: i*j*k*p , (4,3,2,2) ,dtype =int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [69]:
a = np.fromfunction(lambda i ,j,z: i*j*z , (4,3,2) ,dtype =int)

In [70]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [71]:
a.ndim

3

In [72]:
a.size

24

In [73]:
a.shape

(4, 3, 2)

In [74]:
a.dtype

dtype('int32')

In [75]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [76]:
a = np.fromfunction(lambda i ,j: i*j , (3,2) ,dtype =int)

In [77]:
a

array([[0, 0],
       [0, 1],
       [0, 2]])

In [78]:
import pandas as pd

In [79]:
pd.DataFrame(a)

0  1
0  0  0
1  0  1
2  0  2

In [80]:
np.random.randn(100,4)

array([[-0.7267379 ,  1.07520801, -0.31269674, -0.73649014],
       [-0.41526959,  0.62593808,  0.25694147,  0.67675536],
       [ 1.74674107, -0.70436595, -0.33513583, -0.47121704],
       [-1.49715889,  0.53759633, -0.71963015,  2.02781943],
       [ 0.20648043, -0.92714705, -0.21536602, -0.02120393],
       [ 0.61508684, -0.38477741,  1.04292748, -1.62883224],
       [ 0.47408523, -0.73508165,  0.46154852,  0.19736659],
       [ 0.20991115,  0.09524717, -1.36015801,  1.59075334],
       [ 1.21737999,  0.23715861, -0.3274497 ,  0.76784548],
       [ 1.54852309,  0.46805391, -1.3114352 ,  0.10903904],
       [-0.44039184, -1.1449794 ,  1.11354678, -1.94783811],
       [-0.55749492,  0.08516193, -0.00505949,  1.46225259],
       [ 0.83197232,  0.57343889, -0.65696134, -0.13366166],
       [-0.21927837,  1.83421509,  0.44220838,  0.12341007],
       [-0.49303662, -0.16986271, -0.07619017, -0.52724161],
       [-1.17919151,  0.364852  , -0.61334105, -0.25160441],
       [ 1.56846469,  0.

In [82]:
np.random.randint(4,50)

40

In [83]:
np.random.randn(4,5)

array([[-0.24524243,  0.7730735 ,  0.72475032,  2.33069484, -0.33445935],
       [-0.48352662,  1.40779063, -1.92877536, -0.15034187,  0.7565851 ],
       [-0.19294329,  0.86021572, -0.09535839,  1.37961886,  0.39147467],
       [ 0.88095193,  0.21903253,  0.86241121,  0.83505812,  1.25134159]])

In [84]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  1.714959 -0.528685 -1.055564 -0.524165 -0.429949
1  0.312101 -0.955576 -0.086557  0.165056  0.242110
2  1.628850  0.574018 -0.774791 -0.648070  1.403055
3 -0.868841  1.252539 -1.166043 -0.040780  1.178714

In [85]:
a5 = np.fromfunction(lambda i ,j,z: i*j*z , (4,3,2) ,dtype =int)

In [91]:
a5.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [92]:
a5.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [94]:
pd.DataFrame(a5.reshape(3,8))

0  1  2  3  4  5  6  7
0  0  0  0  0  0  0  0  0
1  0  1  0  2  0  0  0  2
2  0  4  0  0  0  3  0  6

In [95]:
a6 = np.fromfunction(lambda i ,j,z: i*j*z , (4,3,2) ,dtype =int)

In [102]:
a6.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [103]:
a7 = np.fromfunction(lambda i ,j,z: i*j*z , (4,3,2) ,dtype =int)

In [104]:
a7.reshape(4,-1) # -1 takes 6 here in this case (4 *6 = 24)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [105]:
a7.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [106]:
a7.reshape(2,4,-1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [111]:
list(range(4,10,2))

[4, 6, 8]

In [112]:
np.arange(4,10 ,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [117]:
a10 =np.arange(4,10.5,.2)

In [118]:
a10

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [119]:
a10[1:4]

array([4.2, 4.4, 4.6])

In [121]:
arr =np.random.rand(4,5)

In [122]:
arr

array([[0.67181163, 0.17642536, 0.99283818, 0.34280441, 0.38037884],
       [0.85660107, 0.6926706 , 0.48537463, 0.8820737 , 0.81463828],
       [0.65186272, 0.62798614, 0.46910708, 0.35801607, 0.60923464],
       [0.55391794, 0.87837259, 0.26733156, 0.379251  , 0.98800701]])

In [ ]:
# extract vlaues >0.5 in above array

In [123]:
arr >.5

array([[ True, False,  True, False, False],
       [ True,  True, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True]])

In [124]:
arr[arr>0.5]

array([0.67181163, 0.99283818, 0.85660107, 0.6926706 , 0.8820737 ,
       0.81463828, 0.65186272, 0.62798614, 0.60923464, 0.55391794,
       0.87837259, 0.98800701])

In [125]:
arr

array([[0.67181163, 0.17642536, 0.99283818, 0.34280441, 0.38037884],
       [0.85660107, 0.6926706 , 0.48537463, 0.8820737 , 0.81463828],
       [0.65186272, 0.62798614, 0.46910708, 0.35801607, 0.60923464],
       [0.55391794, 0.87837259, 0.26733156, 0.379251  , 0.98800701]])

In [127]:
arr[[1,2], [2]]

array([0.48537463, 0.46910708])

In [128]:
arr = np.random.rand(8,5)

In [129]:
arr

array([[0.38299925, 0.50058068, 0.12766466, 0.91972387, 0.37704135],
       [0.2953407 , 0.92361939, 0.46962858, 0.28870875, 0.31684598],
       [0.39859257, 0.26781094, 0.23758455, 0.47885485, 0.47294902],
       [0.34879896, 0.40531377, 0.37815807, 0.29829956, 0.36218784],
       [0.8467774 , 0.49350745, 0.3495204 , 0.6957274 , 0.85332977],
       [0.04824035, 0.77529906, 0.43325752, 0.31575267, 0.87519644],
       [0.33149812, 0.86184533, 0.4744631 , 0.65015764, 0.52067526],
       [0.0634255 , 0.99830056, 0.07696857, 0.647505  , 0.63859016]])

In [135]:
arr[1:8,[0,1,2]]

array([[0.2953407 , 0.92361939, 0.46962858],
       [0.39859257, 0.26781094, 0.23758455],
       [0.34879896, 0.40531377, 0.37815807],
       [0.8467774 , 0.49350745, 0.3495204 ],
       [0.04824035, 0.77529906, 0.43325752],
       [0.33149812, 0.86184533, 0.4744631 ],
       [0.0634255 , 0.99830056, 0.07696857]])

In [132]:
arr[1:8,0:3]

array([[0.2953407 , 0.92361939, 0.46962858],
       [0.39859257, 0.26781094, 0.23758455],
       [0.34879896, 0.40531377, 0.37815807],
       [0.8467774 , 0.49350745, 0.3495204 ],
       [0.04824035, 0.77529906, 0.43325752],
       [0.33149812, 0.86184533, 0.4744631 ],
       [0.0634255 , 0.99830056, 0.07696857]])

In [137]:
a2 = arr[1:8,[0,1,2]]

In [138]:
a2

array([[0.2953407 , 0.92361939, 0.46962858],
       [0.39859257, 0.26781094, 0.23758455],
       [0.34879896, 0.40531377, 0.37815807],
       [0.8467774 , 0.49350745, 0.3495204 ],
       [0.04824035, 0.77529906, 0.43325752],
       [0.33149812, 0.86184533, 0.4744631 ],
       [0.0634255 , 0.99830056, 0.07696857]])

In [139]:
a2[0][0]

0.2953406977137739

In [140]:
a2[0][0] = 100

In [141]:
a2

array([[1.00000000e+02, 9.23619393e-01, 4.69628581e-01],
       [3.98592569e-01, 2.67810943e-01, 2.37584552e-01],
       [3.48798964e-01, 4.05313767e-01, 3.78158067e-01],
       [8.46777397e-01, 4.93507449e-01, 3.49520398e-01],
       [4.82403505e-02, 7.75299060e-01, 4.33257522e-01],
       [3.31498120e-01, 8.61845333e-01, 4.74463099e-01],
       [6.34254985e-02, 9.98300562e-01, 7.69685718e-02]])

In [146]:
a = np.array([[1,2] , [3,4]])
b = np.array([[2,3] , [4,5]])

In [147]:
a

array([[1, 2],
       [3, 4]])

In [148]:
b

array([[2, 3],
       [4, 5]])

In [149]:
a*b

array([[ 2,  6],
       [12, 20]])